"""Initial

Revision ID: 1a6a915f9fc9
Revises: 
Create Date: 2025-01-24 19:53:20.861322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a6a915f9fc9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gerencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sedes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('departamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('gerencia_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gerencia_id'], ['gerencias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('departamento_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['departamento_id'], ['departamentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cargos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empleados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ficha', sa.String(length=10), nullable=True),
    sa.Column('apellido', sa.String(length=100), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('sede_id', sa.Integer(), nullable=True),
    sa.Column('gerencia_id', sa.Integer(), nullable=True),
    sa.Column('departamento_id', sa.Integer(), nullable=True),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('cargo_id', sa.Integer(), nullable=True),
    sa.Column('equipo_asignado', sa.String(length=200), nullable=True),
    sa.Column('extension', sa.String(length=10), nullable=True),
    sa.Column('correo', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['cargo_id'], ['cargos.id'], ),
    sa.ForeignKeyConstraint(['departamento_id'], ['departamentos.id'], ),
    sa.ForeignKeyConstraint(['gerencia_id'], ['gerencias.id'], ),
    sa.ForeignKeyConstraint(['sede_id'], ['sedes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sede_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('nombre_equipo', sa.String(length=50), nullable=True),
    sa.Column('modelo', sa.String(length=50), nullable=True),
    sa.Column('marca', sa.String(length=50), nullable=True),
    sa.Column('serial', sa.String(length=100), nullable=True),
    sa.Column('ram', sa.String(length=20), nullable=True),
    sa.Column('disco', sa.String(length=50), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('activo_fijo', sa.String(length=20), nullable=True),
    sa.Column('empleado_id', sa.Integer(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], ),
    sa.ForeignKeyConstraint(['sede_id'], ['sedes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assets')
    op.drop_table('empleados')
    op.drop_table('cargos')
    op.drop_table('areas')
    op.drop_table('departamentos')
    op.drop_table('sedes')
    op.drop_table('gerencias')
    # ### end Alembic commands ###
